name: Cypress Tests

on:
  push:
    branches:
      - develop
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        containers: [1, 2, 3]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Generate env variable
        run: |
          echo "REACT_APP_API_URL=$REACT_APP_API_URL" >>  .env
          echo "PORTONE_IMP=$PORTONE_IMP" >>  .env
          echo "PORTONE_PG_CODE=$PORTONE_PG_CODE" >>  .env
        env:
          REACT_APP_API_URL: ${{ secrets.REACT_APP_API_URL }}
          PORTONE_IMP: ${{ secrets.PORTONE_IMP }}
          PORTONE_PG_CODE: ${{ secrets.PORTONE_PG_CODE }}
      - name: Cypress run
        uses: cypress-io/github-action@v5
        with:
          build: npm run build
          record: true
          parallel: true
          start: npm start
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
